# Basic Operations on Numpy Array

In [1]:
# operations on numpy array
# containers: lists(costless insertion and append),dictionaries(fast lookup)

In [2]:
# Numpy provides
# extension package to python for multi dimensional array
# closer to hardware
# Also known as array oriented computing

In [4]:
import numpy as np
a=np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [5]:
# Memory efficient container that provides fast numerical operations
L=range(1000)
%timeit[i**2 for i in L]

1.57 ms ± 6.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
# %timeit will automatically calculate number of runs required for your code based on a total of 2 seconds execution window.

In [8]:
a = np.arange(1000)
%timeit a**2   # so it is memory efficient

5.25 µs ± 574 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [10]:
a.ndim

1

In [11]:
# shape
a.shape

(4,)

In [12]:
len(a)

4

In [13]:
# 2-D 3-D array
b=np.array([[1,2,3],[4,5,6]])

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [18]:
len(b)

2

In [19]:
# Fuction for creating array

In [20]:
# arange,linespace 

In [24]:
# using linespace
a=np.linspace(0,1,6) # start number,end number,no.of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
# common array
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
c=np.eye(3)
c      # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
d=np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [34]:
# creating diagonal matrix
a=np.diag([1,2,3,4])

In [35]:
# finding the diagonals
np.diag(a)

array([1, 2, 3, 4])

In [37]:
# create array using random
# create array of given shape and populate with it random samples from a uniform distribution over[0,1)
a=np.random.rand(4)
a

array([0.34795202, 0.62593862, 0.43620483, 0.23342359])

In [39]:
# now if i want from standard normal distribution "Gaussian"
a=np.random.randn(4)
a

array([ 0.71959446, -0.69468505, -0.8000649 , -1.10039838])

In [40]:
# Basic Data Type

In [41]:
a=np.array([1,2,3])
a
a.dtype

dtype('int32')

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

In [42]:
# Indexing and slicing
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [43]:
a[2,2]

3

In [51]:
# Slicing
a=np.array([1,2,3,6,7,8,9,10])
 # [start index:end index:step size]
a[1:8:2]

array([ 2,  6,  8, 10])

In [58]:
# we can also combine assignment and slicing
b=np.arange(5)
a=np.arange(10)
b
a[5:]=b[::-1] # assigning 
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [56]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# Copies and Views
# Slicing creates a view on the original view. which is a just a way to access data.Thus the original array is not copied in memory
# you can use np.may_share_memory() to check if two arrays share the same memory block

In [60]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
b=a[::2]

In [62]:
b

array([0, 2, 4, 6, 8])

In [63]:
np.shares_memory(a,b)

True

In [64]:
b[0]=10

In [65]:
b

array([10,  2,  4,  6,  8])

In [66]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [67]:
# even though we had updated b because a and b shares same memory a itself get automatically updated 

In [68]:
a=np.arange(10)
c=a[::2].copy()

In [69]:
c

array([0, 2, 4, 6, 8])

In [71]:
np.shares_memory(a,c)  # force a copy

False

In [72]:
# Element wise operation
# Basic Operation

In [73]:
a=np.array([1,2,3,4]) # it adds 1 to each of the element
a+1

array([2, 3, 4, 5])

In [74]:
# All arthimetic operations are elementwise

In [75]:
b=np.ones(4)+1

In [76]:
b

array([2., 2., 2., 2.])

In [77]:
# Matrix multiplication
a=np.array([[1,2],[2,4]])

In [78]:
a

array([[1, 2],
       [2, 4]])

In [79]:
print(a*a)

[[ 1  4]
 [ 4 16]]


In [81]:
print(a.dot(a)) # a.dot(a) is the matrix multiplication

[[ 5 10]
 [10 20]]


In [82]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
print(a==b)

[False False False False]


In [83]:
# Array wise comparison
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
np.array_equal(a,b)

True

In [84]:
# Basic Reduction
# argmin is used to find the index of minimium element
x=np.array([1,2,3,4,5])

In [86]:
x.argmin()

0

In [87]:
x.argmax()

4

In [90]:
#Logical operators
np.all([True,False,True,True])

False

In [91]:
np.any([True,False,True])

True

In [93]:
a=np.array([[1,2,3],[4,5,6]])

In [94]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [95]:
# Sorting Data

In [96]:
a=np.array([[5,4,6],[2,3,2]])

In [97]:
b=np.sort(a,axis=1)

In [98]:
b

array([[4, 5, 6],
       [2, 2, 3]])

In [99]:
# sorting with fancy indexing
a=np.array([4,3,1,2])
j=np.argsort(a)

In [100]:
j

array([2, 3, 1, 0], dtype=int64)

In [101]:
a[j]

array([1, 2, 3, 4])